import React from "react";

import { Metadata } from "next";

import { questionData } from "@/constants";

import { DetailContent } from "./components";

export const metadata: Metadata = {
  title: "Dashboard Detail - Solve Education!",
  description: "Generated by create next app",
};

const DashboardDetail = async () => {
  const data = questionData;

  return (
    <>
      <DetailContent data={data} />
    </>
  );
};

export default DashboardDetail;
