import type { Metadata } from "next";

import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Inter } from "next/font/google";
import "react-datepicker/dist/react-datepicker-cssmodules.css";
import "react-datepicker/dist/react-datepicker.css";

import MUIThemeProvider from "@/plugins/mui/provider";
import NextAuthProvider from "@/plugins/next-auth/provider";
import CustomSWRConfig from "@/plugins/swr";
import "@/styles/globals.css";
const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solve Education! - By @muhammadzidane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MUIThemeProvider>
          <AppRouterCacheProvider>
            <CustomSWRConfig>
              <NextAuthProvider>{children}</NextAuthProvider>
            </CustomSWRConfig>
            <CssBaseline />
          </AppRouterCacheProvider>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
