import type { Metadata } from "next";

import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Inter } from "next/font/google";
import "react-datepicker/dist/react-datepicker-cssmodules.css";
import "react-datepicker/dist/react-datepicker.css";

import { Toast } from "@/components";
import NextAuthProvider from "@/plugins/next-auth/provider";
import CustomSWRConfig from "@/plugins/swr";
import "@/styles/globals.css";
const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Bandung Coders - By @bacodteam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <CustomSWRConfig>
            <NextAuthProvider>{children}</NextAuthProvider>
            <Toast />
          </CustomSWRConfig>
          <CssBaseline />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
